name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Build and Deploy to Deno Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "pnpm"
          registry-url: https://registry.npmjs.org/

      - name: Install NPM Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build.deno

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "qwik-todos"
          root: "server"
          entrypoint: "entry.deno.js"
