name: Deploy to CloudFlare

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "pnpm"
          registry-url: https://registry.npmjs.org/

      - name: Install NPM Dependencies
        run: pnpm install --frozen-lockfile

      - name: Format check
        run: pnpm run fmt.check

      - name: Build
        run: pnpm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: qwik-todos
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
